package co.edu.uniquindio.compiladores.lexico
/*
 * @ Ximena Silva, Elier Duque
 */
enum class Categoria {

    ENTERO, DECIMAL, IDENTIFICADOR, OPERADOR_ARITMETICO, OPERADOR_RELACIONAL, OPERADOR_LOGICO, OPERADOR_ASIGNACION,
    PARENTESIS_IZQ, PARENTESIS_DER, LLAVE_IZQ, LLAVE_DER,CORCHETE_IZQ,CORCHETE_DER, FIN_SENTENCIA, SEPARADOR,
    CADENA_CARACTERES, COMENTARIOLINEA, COMENTARIO_BLOQUE, DESCONOCIDO , PALABRA_RESERVADA,INCREMENTO,DECREMENTO,PUNTO,DOS_PUNTOS, CARACTER
}